name: Android CI

on:
  workflow_dispatch:  

jobs:
  appium-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set a timeout to prevent runs from hanging indefinitely

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Create and start emulator
      run: |
        echo "y" | sdkmanager "system-images;android-29;default;x86"
        echo "no" | avdmanager create avd -n testEmulator -k "system-images;android-29;default;x86"
        $ANDROID_HOME/emulator/emulator -avd testEmulator -no-audio -no-window -gpu swiftshader_indirect &
        $ANDROID_HOME/platform-tools/adb wait-for-device

    - name: Install Appium
      run: npm install -g appium

    - name: Run Appium tests
      run: |
        appium &  # Start Appium server in the background
        sleep 10  # Allow some time for Appium server to start
        npm run test  # Run your test script, assuming it's set up under npm scripts

    - name: Capture logs
      if: failure()  # Only run this step if the previous steps failed
      run: adb logcat -d > logcat.log

    - name: Upload log artifacts
      if: always()  # Always run this step, regardless of job status
      uses: actions/upload-artifact@v2
      with:
        name: android-logs
        path: logcat.log

    - name: Shutdown emulator
      if: always()  # Ensure emulator is shut down after tests
      run: adb -s emulator-5554 emu kill
